version: 2
references:
  config_android: &config_android
    docker:
      - image: circleci/android:api-29
    working_directory: ~/unes
    environment:
      JVM_OPTS: -Xmx2560m
      GRADLE_OPTS: -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

jobs:
  build:
    <<: *config_android
    
    steps:
      - checkout

      - run:
          name: Decode Config Files
          command: |
            if [[ "${GOOGLE_SERVICES}" == "" ]]
            then
              mv ~/unes/app/google-services-mock.json ~/unes/app/google-services.json
            else
              echo $GOOGLE_SERVICES | base64 --decode > ~/unes/app/google-services.json
            fi

            if [[ "${PLAY_PUBLISHER}" != "" ]]
            then
              echo $PLAY_PUBLISHER | base64 --decode > ~/unes/unes_uefs_publisher.json
            fi

            if [[ "${APP_SIGNATURE}" != "" ]]
            then
              echo $APP_SIGNATURE | base64 --decode > ~/unes/sign.jks
            else
              mv ~/unes/sign_mock ~/unes/sign.jks
            fi
      
      - run: 
          name: Downloading Dependencies
          command: |
            ./gradlew dependencies
            
      - run:
          name: Run JVM Checks & Lint
          command: |
            ./gradlew check

      - run:
          name: Save Lint Results
          command: scripts/save_lint_results.sh

      - run:
          name: Build App or Publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ] || [ "${CIRCLE_BRANCH}" == "master" ]
            then
              echo "Starting the publish build!"
              ./gradlew publishReleaseBundle
            else
              echo "Starting a release build"
              ./gradlew :app:assembleRelease
            fi

      - store_artifacts:
          path: ci_results/lint

      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build


