version: 2
references:
  config_android: &config_android
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/unes
    enviroment:
      JVM_OPTS: -Xmx1536m
      GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.workers.max=2"
      TERM: dumb

jobs:
  build:
    <<: *config_android
    
    steps:
      - checkout
      
      - run: 
          name: Downloading Dependencies
          command: |
            ./gradlew dependencies
            
      - run:
          name: Run JVM Checks & Lint
          command: |
            ./gradlew check

      - run:
          name: Build Debug APK
          command: |
            ./gradlew :app:assembleDebug

      - run:
          name: Save Lint Results
          command: scripts/save_lint_results.sh

      - store_artifacts:
          path: ci_results/lint

      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build


