version: 2
references:
  config_android: &config_android
  docker:
    -image: circleci/android:api-28-alpha
  working_directory: ~/melon
  enviroment:
    JVM_OPTS: -Xmx3200m
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    TERM: dumb

jobs:
  build:
    <<: *config_android
    
    steps:
      - checkout

      - run: 
        name: Downloading Dependencies
        command: ./gradlew dependencies

      - run:
          name: Build debug APK
          command: ./gradlew :app:assembleDebug


      - store_artifacts:
          path: ci_results/lint

      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build



