[versions]
aboutlibraries = "11.2.2"
agp = "8.7.2"
android-desugar = "2.1.2"
android-image-cropper = "4.6.0"
androidx-lifecycle = "2.8.7"
androidx-hilt-compiler = "1.2.0"
annotation = "1.9.1"
app-update-ktx = "2.1.0"
appcompat = "1.7.0"
autostarter = "1.1.0"
billing = "7.1.1"
browser = "1.8.0"
card-slider = "0.3.1"
constraintlayout = "2.2.0"
core-testing = "2.2.0"
credentials = "1.3.0"
dagger = "2.52"
datastore-preferences = "1.1.1"
espresso-core = "3.6.1"
firebase-bom = "33.5.1"
firebase-crashlytics-gradle = "3.0.2"
firebase-ui-storage = "8.0.2"
flexbox = "3.0.0"
floatingsearchview = "2.1.1"
fragment = "1.8.5"
glide = "4.16.0"
google-ksp = "2.0.21-1.0.26"
google-services = "4.4.2"
guava = "33.3.1-android"
gson = "2.11.0"
hilt-android = "2.52"
hilt-work = "1.2.0"
jsoup = "1.18.1"
juice = "1.8.0"
junit = "4.13.2"
junit-version = "1.2.1"
kotlin = "2.0.21"
kotlinter-gradle = "4.3.0"
kotlinx-coroutines-test = "1.9.0"
ktx = "1.15.0"
chucker = "4.0.0"
listenablefuture = "9999.0-empty-to-avoid-conflict-with-guava"
lottie = "6.5.0"
material = "1.12.0"
materialdatetimepicker = "4.2.3"
markwon = "4.6.2"
mockk = "1.13.12"
mpandroidchart = "v3.1.0"
navigation = "2.8.3"
okhttp = "4.12.0"
oversee = "1.1.0"
paging = "3.3.2"
pallete = "1.0.0"
persistentcookiejar = "v1.0.1"
play-publisher = "3.10.1"
play-services-games-v2 = "20.1.2"
play-services-auth = "21.2.0"
play-services-location = "21.3.0"
play-services-maps = "19.0.0"
preference = "1.2.1"
retrofit = "2.11.0"
review-ktx = "2.0.2"
room = "2.6.1"
rxkotlin = "2.4.0"
snowpiercer = "2.4.0"
sqldelight = "2.0.1"
koin = "3.5.3"
ktor = "2.3.9"
coroutines = "1.9.0"
kotlinx-datetime = "0.6.0"
swiperefreshlayout = "1.1.0"
taptargetview = "1.14.0"
timber = "5.0.1"
uuid = "0.8.2"
native-coroutines = "1.0.0-ALPHA-26"
skie = "0.6.2"
string-normalization = "1.0.5"
hashing = "0.5.1"
work = "2.10.0"

[libraries]
aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlibraries" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "android-image-cropper" }
android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugar" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-reactivestreams = { module = "androidx.lifecycle:lifecycle-reactivestreams", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-reactivestreams-ktx = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "pallete" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "work" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "app-update-ktx" }
autostarter = { module = "com.github.judemanutd:autostarter", version.ref = "autostarter" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
card-slider = { module = "com.ramotion.cardslider:card-slider", version.ref = "card-slider" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
feature-delivery-ktx = { module = "com.google.android.play:feature-delivery-ktx", version.ref = "app-update-ktx" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-functions-ktx = { module = "com.google.firebase:firebase-functions-ktx" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
firebase-ui-storage = { module = "com.firebaseui:firebase-ui-storage", version.ref = "firebase-ui-storage" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
floatingsearchview = { module = "com.github.arimorty:floatingsearchview", version.ref = "floatingsearchview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt-compiler" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
juice = { module = "dev.forcetower.unes:juice", version.ref = "juice" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
listenablefuture = { module = "com.google.guava:listenablefuture", version.ref = "listenablefuture" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
materialdatetimepicker = { module = "com.wdullaer:materialdatetimepicker", version.ref = "materialdatetimepicker" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon-ext-latex = { module = "io.noties.markwon:ext-latex", version.ref = "markwon" }
markwon-ext-strikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwon" }
markwon-html = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwon-image = { module = "io.noties.markwon:image", version.ref = "markwon" }
markwon-image-glide = { module = "io.noties.markwon:image-glide", version.ref = "markwon" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
oversee = { module = "dev.forcetower.unes:oversee", version.ref = "oversee" }
persistentcookiejar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentcookiejar" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }
play-services-games-v2 = { module = "com.google.android.gms:play-services-games-v2", version.ref = "play-services-games-v2" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review-ktx" }
rxkotlin = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rxkotlin" }
snowpiercer = { module = "dev.forcetower.unes:snowpiercer", version.ref = "snowpiercer" }
sqldelight-androidDriver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-nativeDriver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-coroutinesExtensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
taptargetview = { module = "com.getkeepsafe.taptargetview:taptargetview", version.ref = "taptargetview" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
string-normalization = { module = "com.doist.x:normalize", version.ref = "string-normalization" }
hashing = { module = "org.kotlincrypto.hash:md", version.ref = "hashing"}

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
androidx-navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
androidx-room = { id = "androidx.room", version.ref = "room" }
firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinter-gradle = { id = "org.jmailen.kotlinter", version.ref = "kotlinter-gradle" }
hilt-android-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
play-publisher = { id = "com.github.triplet.play", version.ref = "play-publisher" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
